site_name: Torchbox Constitution
site_url: https://torchbox.github.io/torchbox-constitution
repo_url: https://github.com/torchbox/torchbox-constitution
repo_name: torchbox/torchbox-constitution
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: assets/torchbox-logo.svg
  favicon: assets/torchbox-favicon.png

extra_css:
  - https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap
  - assets/overrides.css
  - assets/glossary.css

extra_javascript:
  - assets/glossary.js
  - assets/glossary.json

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/torchbox/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/torchbox/
  generator: false

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Introduction: index.md
  - 1. Co-owner Rights & Responsibilities: rights-and-responsibilities.md
  - 2. Purpose & Principles: purpose-and-principles.md
  - 3. Structure & Governance: structure-and-governance.md
  - 4. Financial Management: financial-management.md
  - Glossary: glossary.md
